### ISSUE TITLE
[Grundboken] Skadetabeller

### ISSUE THREAD

**Issue by fsergler** [JohanFalt/Foundry_EON-RPG#139]
Jag har skapat en simple version av skadetabellerna (Hugg/Kross/Stick/Slagsmål) från Grundboken för egen bruk (med hjälp av ChatGPT).
Just nu består det av flertalet rollable tables samt ett macro. Om du är intresserad av att lägga till dem till projektet så kan du få filerna av mig.
Bifogar bilder på hur det ser ut i foundry:
![1](https://github.com/JohanFalt/Foundry_EON-RPG/assets/128369769/f182bde8-c17e-4060-b3b5-9f1f8aff40a2)
![2](https://github.com/JohanFalt/Foundry_EON-RPG/assets/128369769/2c0c90eb-db86-4bed-bdcc-c176073b8199)
![3](https://github.com/JohanFalt/Foundry_EON-RPG/assets/128369769/894ba498-74a9-4660-a425-0327a15718aa)

**Comment by JohanFalt** [comment]
Nice!

Jo det skulle jag gärna vilja lägga till i systemet.

**Comment by fsergler** [comment]
Då skickar jag dem senare ikväll då jag kommit hem. Hur vill du att jag skickar/lägger upp filerna?

**Comment by fsergler** [comment]
Här är filerna:
[Eonskador.zip](https://github.com/JohanFalt/Foundry_EON-RPG/files/14300064/Eonskador.zip)
Finns en readme med men misstänker att den kanske är mer användbar om man manuellt vill lägga till det hela.

**Comment by fsergler** [comment]
Noterade en mindre sak som borde updateras i macrot, och det är texten "Ange tärningskast du vill göra (t.ex 1d20+5)" bör ändras till 1d10.
