### ISSUE TITLE
Editera attribut för varelser

### ISSUE THREAD

**Issue by Simowah** [JohanFalt/Foundry_EON-RPG#140]
Lyckas ej editera attribut för varelser (Actor --> Varelse). 
Då man trycker på penn-symbolen händer ingenting.

Det vore även toppen om man kunde lägga till en egen vändningstabell för varelser, samt ev. färdigheter, skydd och ev. vapen.

**Comment by JohanFalt** [comment]
Jag lägger till detta till den nästkommande versionen så jag får varelseformulären klara.

**Comment by JohanFalt** [comment]
Kommer till v3.1
