### ISSUE TITLE
Döpa om karaktärsblad.

### ISSUE THREAD

**Issue by kzxcmx** [JohanFalt/Foundry_EON-RPG#152]
Hittar ej funktion för att döpa om karraktärsbladen. 
Tokens går att ändra namn på men detta knyter inte ihop med karraktärsbladet.

**Comment by JohanFalt** [comment]
Inne på Bakgrund fältet Namn.

![image](https://github.com/JohanFalt/Foundry_EON-RPG/assets/57871596/25ef51b7-9fb8-4123-9d6a-f4f650e48489)
