### ISSUE TITLE
Justera pansarvärde

### ISSUE THREAD

**Issue by kzxcmx** [JohanFalt/Foundry_EON-RPG#156]
Går ej att justera pansarvärde på rustningar. 
Behövs när spelare antingen rullar fram tung rustning eller får bättre rustning smidd.

**Comment by JohanFalt** [comment]
Finns redan som issue: https://github.com/JohanFalt/Foundry_EON-RPG/issues/138

Kommer nu i den kommande versionen

**Comment by fsergler** [comment]
@JohanFalt Är inte helt säker på att denna är klar. Jag har inte updaterat Rustningar i sig utan bara grundrustningen. Är rätt så säker på att Rustningar fortfarande har statiska värden som inte går att ändra.

**Comment by JohanFalt** [comment]
Missat att placera huvud-issue till 3.1 https://github.com/JohanFalt/Foundry_EON-RPG/issues/67 har gjort det nu.
