### ISSUE TITLE
Checklista

### ISSUE THREAD

**Issue by JohanFalt** [JohanFalt/Foundry_EON-RPG#2]
(Thalaski)

Checklista för saker som med fördel automatiseras i formuläret:
¤ Härledda attribut räknas ut automatiskt utifrån Grundattributen.
¤ Minustärningar från skador. Såväl mentala som fysiska. Dessa kan temporärt påverka färdighetsvärden och härledda värden.
¤ Belastning. påverkar grundutmattning, förflyttning, reaktion och rörelsefärdigheter. Beräkning sker utifrån RPs vikt. Se Strid sid 152.
¤ Grundskada. Kan förändras om grundattributen förändras. 
¤ Vapenskada. För de flesta vapen gäller grundskada + vapenskada
¤ Grundrustning
¤ Beräkning av svårighet för förbättringsslag (skälet till att jag började med mitt google-sheets-formulär)

**Comment by KodKoftan** [comment]
Behöver finnas möjlighet att lägga till +/- på Härledda attribut. Finns många bakgrundsslag som ändrar härledda attribut utan att ändra grundattribut.

**Comment by JohanFalt** [comment]
> Behöver finnas möjlighet att lägga till +/- på Härledda attribut. Finns många bakgrundsslag som ändrar härledda attribut utan att ändra grundattribut.

Så en bonus helt enkelt.

Säg t ex färdigheter, de har ett värde man har på dem. Det värdet man höjer etc, men så kan man ha en tärningsbonus med, kan komma från vapen, välsignelse, bakgrund vad som och den skall ligga om en bonus på det hela så man alltid kan gå tillbaka till - ok vad hade du i grundvärde. 
Härledda attribut blir likadana.

**Comment by JohanFalt** [comment]
Kvar:
¤ Minustärningar från skador. Såväl mentala som fysiska. Dessa kan temporärt påverka färdighetsvärden och härledda värden.
¤ Belastning. påverkar grundutmattning, förflyttning, reaktion och rörelsefärdigheter. Beräkning sker utifrån RPs vikt. Se Strid sid 152.
¤ Beräkning av svårighet för förbättringsslag (skälet till att jag började med mitt google-sheets-formulär)
