### ISSUE TITLE
Flytta "Ny färdighet" till högst upp i färdighetslistan

### ISSUE THREAD

**Issue by fsergler** [JohanFalt/Foundry_EON-RPG#202]
Ändra "Ny färdighet" till "_Ny färdighet", detta gör att den kommer lägga sig högst upp i listan av färdighet. Vilket gör att den blir lättare att hitta.

**Comment by JohanFalt** [comment]
Löst genom att när man skapar ett nytt föremål öppnas editeringsfönstret direkt så man kan ge det den riktiga namnet.
