### ISSUE TITLE
Filtrera varelsemall efter varelsegrupp

### ISSUE THREAD

**Issue by fsergler** [JohanFalt/Foundry_EON-RPG#204]
Just nu kan man ha en "Liten Svartbjörn" eller en "Mycket stor Korp".

**Comment by JohanFalt** [comment]
Är enligt design meningen.

**Comment by JohanFalt** [comment]
Förtydligar - de respektive djuren kommer finnas i normalutförande i kompendiet om man sedan ändra dess storlek beroende på vad man vill använda gör man då det bara.
