### ISSUE TITLE
Välmående går att sätta över 10

### ISSUE THREAD

**Issue by Thalaski** [JohanFalt/Foundry_EON-RPG#25]
Nu går det att höja välmående över 10 och då få fler fokusprickar. Jag vet inte om det är en bugg eller en feature, men jag tror inte att man kan ha mer välmående enligt reglerna.

**Comment by JohanFalt** [comment]
Helt klart en bugg :)

**Comment by JohanFalt** [comment]
På ämnet. När man sänker Välmående har jag bara gjort att antalet fokusprickar blir färre. Är det en bra lösning?

Funderade på om man kanske skulle ha kvar antalet men minska hur mycket Fokus man hade och hur högt detta kan bli. Men det känns lite fel.
För om välmående går ner till 9 och sedan upp till 10 igen, har man då Fokus 9 fortfarande eller denna följer med välmående?

**Comment by Thalaski** [comment]
Som jag har förstått det så ligger man fortfarande kvar på 9 fokus i exemplet.

**Comment by JohanFalt** [comment]
Då skall jag ändra lite i hur det hela hanteras...
