### ISSUE TITLE
Önskemål: Att utmattning syns på Tokens

### ISSUE THREAD

**Issue by Thalaski** [JohanFalt/Foundry_EON-RPG#286]
Som SL skulle jag gärna bara kunna klicka på min token och uppdatera utmattning direkt där, utan att behöva klicka in mig på formuläret. Extra viktigt när det handlar om stora strider med många kombatanter.

**Comment by JohanFalt** [comment]
En enkel inställning i systemet bara glömt göra den. Ska bara skriva en enkel instruktion i Wikin och sedan släppa 3.1.1 så kommer det med på alla nya Actors.
