### ISSUE TITLE
[FLIK] Färdigheter

### ISSUE THREAD

**Issue by JohanFalt** [JohanFalt/Foundry_EON-RPG#42]
- [x] Slå färdigheter
- [x] Expertiser
- [x] Hantverk
- [x] Kännetecken
- [x] Inga attribut

**Comment by Thalaski** [comment]
När man skapar en ny färdighet så saknar jag valen för Expertis, hantverk samt kännetecken. För tydlighetens skull så skulle det ockås kunna finnas attributet "Ej attribut" (även om "-Välj-" verkar funka så).
![EOB_EonItemSheet](https://github.com/JohanFalt/Foundry_EON-RPG/assets/101973274/9b106cc5-1052-4188-8061-194e801fb712)

**Comment by Thalaski** [comment]
> Eller skall dessa hamna bland "Övriga"?

De hamnar som övriga färdigheter. Regeltekniskt så räknas de också automatiskt som lättlärda.
